#1. Write a NumPy program to get the **numpy version** and show **numpy build configuration**

In [ ]:
TOPICS:
    np.__version__ , np.show_config() , np.info() , np.all(arr) , np.any() ,
    np.arange().np.reshape , np.nditer() , isinf() , isfinite() , np.nan ,
    np.inf , np.iscomplex() , np.isreal() , np.isscalar() , 
    arr.size*arr.itemsize

In [2]:
import numpy as np

print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/hp/anaconda3\\Library\\include']
None


#2. Write a NumPy program to  get help on the add function

In [ ]:
import numpy as np

In [4]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#3. Write a NumPy program to test whether none of the elements of a given array is zero

In [7]:
import numpy as np

arr = np.array([1,2,3,4])

print("Original Array: ")

print(arr)

print('Test whether none of the elements of a given array is zero: ')
print(np.all(arr))

print('')
arr2 = np.array([0,2,4,6])

print('Original Array: ')
print(arr2)

print('Test whether none of the elements of a given array is zero: ')
print(np.all(arr2))

Original Array: 
[1 2 3 4]
Test whether none of the elements of a given array is zero: 
True

Original Array: 
[0 2 4 6]
Test whether none of the elements of a given array is zero: 
False


#4. Write a NumPy program to test whether any of the elements of a 
given array is non-zero

In [ ]:
import numpy as np

In [8]:
arr = np.array([2,0,0,0])

print('Original Array: ')
print(arr)

print('Check whether any of the elements of a given array is non-zero')
print(any(arr))

print('')

arr2 = np.array([0,0,0,0])
print('Original Array: ')
print(arr2)

print('Check whether any of the elements of a given array is non-zero')
print(any(arr2))

Original Array: 
[2 0 0 0]
Check whether any of the elements of a given array is non-zero
True

Original Array: 
[0 0 0 0]
Check whether any of the elements of a given array is non-zero
False


# any()

The any() function returns True if any item in an iterable are true, otherwise it returns False.

If the iterable object is empty, the any() function will return False.

# all()

The all() function returns True if all items in an iterable are true, otherwise it returns False.

If the iterable object is empty, the all() function also returns True.



mylist = [0, 1, 1]
x = all(mylist)
print(x)

O/P : False

#5. Write a NumPy program to create a 3X4 array using and iterate over it.

In [10]:
import numpy as np
a = np.arange(10,22).reshape((3,4))
print('Original Array: ')
print(a)

print('Each element of the array is: ')
for x in a:
    print(x,end=' ')

Original Array: 
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is: 
[10 11 12 13] [14 15 16 17] [18 19 20 21] 

In [11]:
import numpy as np
a = np.arange(10,22).reshape((3,4))
print('Original Array: ')
print(a)

print('Each element of the array is: ')
for x in np.nditer(a):
    print(x,end=' ')

Original Array: 
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is: 
10 11 12 13 14 15 16 17 18 19 20 21 

Iterating Arrays Using **nditer()**
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element
In basic **for** loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.
/---------------------------
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

---------------------------/

/---------------------------
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)
  
-----------------------------/

#6. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)

In [ ]:
import numpy as np

In [30]:
arr = np.array([2.5,4,6,8, np.nan ,np.inf])
print('Original Array: ')
print(arr)

print('Test whether a given array element-wise for finiteness : ')
print(np.isinf(arr))

Original Array: 
[2.5 4.  6.  8.  nan inf]
Test whether a given array element-wise for finiteness : 
[False False False False False  True]


**isinf():    True if value is inf
  isfinite(): True if not nan or inf **

#7.
Write a NumPy program to test element-wise for positive or negative infinity.

In [29]:
import numpy as np

arr = np.array([1,0,6.9, np.nan,np.inf])
print('Original array : ')
print(arr)
print()
print('Test element wise fo positive or negative infinity')
print(np.isinf(arr))

Original array : 
[1.  0.  6.9 nan inf]

Test element wise fo positive or negative infinity
[False False False False  True]


#8. Write a NumPy program to test element-wise for NaN of a given array.

In [35]:
import numpy as np
arr = np.array([[4,5,6],[7,8,9],[np.nan,np.nan,np.inf]])

print('Original array: ')
print(arr)
print()
print('Check if array conatains NaN : ')
print(np.isnan(arr))

Original array: 
[[ 4.  5.  6.]
 [ 7.  8.  9.]
 [nan nan inf]]

Check if array conatains NaN : 
[[False False False]
 [False False False]
 [ True  True False]]


#9. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not

In [36]:
import numpy as np

In [47]:
arr = np.array([4,6,8,10,2+3j,4+0j,0+6j])

print('Original array: ')
print(arr)

print('\n')
print('check if {} is complex'.format(arr))
print(np.iscomplex(arr))

print('')

print('Check if arr is real: ')
print(np.isreal(arr))

print('')

print('check for scalar: ')
print(np.isscalar(arr))

Original array: 
[ 4.+0.j  6.+0.j  8.+0.j 10.+0.j  2.+3.j  4.+0.j  0.+6.j]


check if [ 4.+0.j  6.+0.j  8.+0.j 10.+0.j  2.+3.j  4.+0.j  0.+6.j] is complex
[False False False False  True False  True]

Check if arr is real: 
[ True  True  True  True False  True False]

check for scalar: 
False


The isscalar() function is used to returns True if the type of num
is a scalar type.

In [59]:
a = (5.2)
print(np.isscalar(a))

a = False
print(np.isscalar(a))

a = 'Hiasflafd'
print(np.isscalar(a))

a = 6.9
print(np.isscalar(a))

a = []
print(np.isscalar(a))

a = ()
print(np.isscalar(a))


True
True
True
True
False
False


#10.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [ ]:
import numpy as np

In [65]:
arr = np.array([1,7,13,105,])

print('Original Array: ')
print(arr)

print('')
print('Size of memory occupied by the array: ')
print("%d bytes" %(arr.size*arr.itemsize))

Original Array: 
[  1   7  13 105]

Size of memory occupied by the array: 
16 bytes


In [68]:
arr = np.array(['string'])
print("%d bytes"%(arr.size * arr.itemsize))

24 bytes


In [72]:
arr = np.array([6.9])
print("%d bytes"%(arr.size *arr.itemsize))

8 bytes
